name: MBASE SDK Build
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel
jobs:
  ubuntu-amd64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the build test branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      
      - name: Dev dependency install
        run: sudo apt install uuid-dev

      - name: MBASE build
        run: |
          cmake -B build_amd64 -DMBASE_FORCE_BUNDLE=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          cmake --build build_amd64 --config Release -j

  windows-amd64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout the build test branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: MBASE build
        run: |
          cmake -B build_amd64 -DMBASE_FORCE_BUNDLE=ON
          cmake --build build_amd64 --config Release -j

  macos-metal-build:
    runs-on: macos-13
    steps:
      - name: Checkout the build test branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: MBASE build
        run: |
          cmake -B build -DMBASE_FORCE_BUNDLE=ON
          cmake --build build --config Release -j